name: release
on:
  push:
    branches:
      - master
  pull_request:
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'release' || '' }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: cargo install cargo-workspaces
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
        if: github.ref == 'refs/heads/master'
      - run: cargo workspaces publish -y --from-git ${{ github.ref != 'refs/heads/master' && '--dry-run' || '' }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
